immich-app/base-images

server/Dockerfile
server/bin/build-perllib-compress-brotli.sh

Add support to extract full EXIF and XML metadata from JPEG XL(JXL) files. For a detailed description of the current issue please see [issue](https://github.com/immich-app/immich/issues/5161).
Currently, those that have all or the majority of the images in JPEG XL format will not be able to see/edit any EXIF/XML metadata (GPS data, original datetimes), searching images by metadata and geo tagging information.

extract full exif and xml metadata from jxl images with metadata compressed

---

server/Dockerfile

Set reverse geocoding files to read-only for user, group and others so that users running as non-root don't have issues with reverse-geociding data import

fix: reverse geocoding permissions

---

server/bin/build-imagemagick.sh
server/bin/build-libraw.sh
server/bin/build-libvips.sh
server/bin/build-lock.json

This PR targets the current latest commit in the libvips 8.15 branch, which includes a fix for ARW and NEF images (and other RAW formats that are similar to TIFF). As part of this, it changes source code downloading to use git clone with a set revision, meaning there is no longer a need to extract and checksum a tar file. 
The `revision` field in the lock file is the SHA1 hash of a commit, which should generally be the commit that the version tag points to. This value can easily be copied through GH, meaning less friction when updating these dependencies.
I built the dev and prod base images locally and built the server with these images. sharp was able to process a sample ARW image.

fix(deps): use fixed libvips

---

.github/workflows/tag.yml

Update the cron schedule to build this image on _Tuesday_, instead of _Thursday_. For a few reasons:
- The main repo does dependency updates on Tuesday
- Releases tend to be during the end of the week
This hopefully makes it easier avoids the situation where a bump is merged right before a release, while making it easy to review with the rest of the dependency PRs

chore: update cron schedule

---

server/bin/build-lock.json

This PR bumps our Jellyfin build of FFmpeg to 6.0.1-2. Besides a number of bug fixes, this build natively supports hardware acceleration for Rockchip RK3588. This lets us simplify the deployment process for this backend and remove some hacky code.

chore(deps): update ffmpeg to 6.0.1-2

---

server/bin/build-lock.json

Small update with fixes for RKMPP and hardware tone-mapping.

chore(deps): update ffmpeg to 6.0.1-3

---

server/bin/build-lock.json

This jellyfin-ffmpeg release is noteworthy as it updates SVT-AV1 to 2.0.0.

chore: update ffmpeg to 6.0.1-5

---

server/Dockerfile

This is needed to use libplacebo for hardware-accelerated tone-mapping, tested with nvenc.

chore: add mesa vulkan drivers

---

server/Dockerfile
server/bin/configure-apt.sh

This dependency is needed for end-to-end QSV acceleration. The version that Debian stable has is too old, so we use sid for this instead. It also sets sid to lower priority to keep other packages from using it.

chore(deps): add `intel-opencl-icd`

---

server/bin/build-lock.json

Update jellyfin-ffmpeg to the latest patch version. 
Notable fix: support Ubuntu noble.

feat: update ffmpeg

---

server/bin/build-lock.json

There's an increasing number of issues stemming from the current release not having support for newer cameras or formats. Support has been added for these since then, but libraw has a very sporadic release cadence and waiting for the next release could mean many months. This PR uses the current state of libraw until the next release.

chore(deps): update libraw

---

server/Dockerfile
server/bin/build-libheif.sh
server/bin/build-lock.json

There's currently an issue with iOS 18 images not being processed due to the libheif version on the server. This PR addresses that by building an up-to-date version of libheif that patches this. It's generally good to have more control over this dependency anyway since it's very important and changes frequently in tandem with the industry.
* Changes libwebp to be sourced from sid as it has a more recent sister dependency, libsharpyuv, that libheif can also use for improved color processing
* This dependency is the solution to an issue I noticed with WebP video thumbnail generation, so this kills two birds with one stone
* dav1d (used for AVIF) essentially comes for free since our FFmpeg build already includes it
Tested that the server starts up without any errors from libvips (it warns if …

feat: build libheif

---

server/Dockerfile

Add country boundaries file to image. A [geoJSON file](https://github.com/nvkelso/natural-earth-vector/blob/ca96624a56bd078437bca8184e78163e5039ad19/geojson/ne_10m_admin_0_countries.geojson) containing boundary polygons for each country from [Natural Earth](https://www.naturalearthdata.com/). 
Will be used for geocoding images with remote locations which the current cities geocoding fails: https://github.com/immich-app/immich/pull/10950
Built and tested locally.

feat: add country boundaries file to image

---

server/bin/build-lock.json

Bump all dependencies (except libraw). Immich uses sharp `v0.33.5` which requires libvips `v8.15.3`.
Question: Should we use the `libio-compress-brotli-perl` package from debian unstable instead of building it ourselves?

feat: update dependencies

---

server/Dockerfile

The `LD_LIBRARY_PATH` in the base image gets overridden by the `vaapi-wsl` HWA config that also sets `LD_LIBRARY_PATH`. I think it's better to set this in the base image and remove the env from `vaapi-wsl`. This way, we can internally change it as needed without it being a breaking change.

chore: add wsl path to `LD_LIBRARY_PATH`

---

server/Dockerfile
server/bin/configure-apt.sh

Install `libio-compress-brotli-perl` from the trixie repo.
IMO we should keep build-perllib-compress-brotli.sh until trixie is offically released.

feat: install `libio-compress-brotli-perl` from the trixie repo instead of bulding it

---

server/Dockerfile

To mirror https://github.com/immich-app/immich/pull/11818

fix: intel compute runtime packages

---

server/Dockerfile

Reduce the number of image layers to reduce the final docker image size by ~70 MB.
Make sure to have `libio-compress-brotli-perl` in the prod image
Checked with `make prod` that everything works correctly

feat: reduce number of image layers

---

server/Dockerfile

Releated issue: [Failed to generate preview for Adobe ACR exported JXL picture. · Issue #11938 · immich-app/immich](https://github.com/immich-app/immich/issues/11938)
The depencies `libjxl-dev` and `libjxl0.7` are a little old and may cause some JXL decode failed(such as Adobe ACR export one). This pull request upgrade them to 0.9 (channel: debian testing) .
I had manually build and test several JXL files.
All images (dev and prod) build success without error.
There're four JXL files, half of them are Adobe ACR exported and others are transcode using libjxl offical tools.
In each two files, one is lossless, 16bit deepth and another is lessly, 8bit deepth.
Here are the file list:
Upload those files and they works fine.
This is my first pull request, if there's and problem, please comment …

Update libjxl-dev and libjxl to 0.9, fix jxl export by Adobe ACR decode failed

---

server/bin/build-lock.json
server/bin/install-ffmpeg.sh

This should fix a few current bugs, add some new codec and filter options and make using Vulkan more viable. It may or may not have a performance difference; I haven't tested.
Tested on CPU and CUDA with every target video codec, tone-mapping enabled/disabled and hardware decoding enabled/disabled.

chore: update to jellyfin-ffmpeg7

---

.github/workflows/test.yml
server/bin/build-imagemagick.sh
server/bin/build-libheif.sh
server/bin/build-libjxl.sh
server/bin/build-libraw.sh
server/bin/build-libvips.sh
server/bin/install-ffmpeg.sh

This PR:
- fix lint issues
- add a github actions like in the immich repo to test with shellcheck that all shell files are valid
- add an option to specify the JPEGLI_LIBJPEG version with `--JPEGLI_LIBJPEG_LIBRARY_SOVERSION` and `--JPEGLI_LIBJPEG_LIBRARY_VERSION` (ubuntu and debian use different versions) https://github.com/libvips/libvips/discussions/4177

fix: lint and jpegli version

---

server/bin/build-libjxl.sh
server/bin/jpegli-empty-dht-marker.patch

jpegli doesn't handle DHT markers without any huffman tables, but this is apparently common for Whatsapp images. The solution in [this](https://github.com/libjxl/libjxl/pull/2704) PR is to ignore it and move on, as other decoders do. This PR adds this as a patch until this is handled upstream.
Tested with images from [this](https://github.com/immich-app/immich/issues/13465) thread.

fix: handle empty dht in jpegli

---

server/bin/build-lock.json

This FFmpeg release has relevant improvements for tone-mapping that will be nice to include in the next release.

chore: bump ffmpeg to 7.0.2-4

---

server/bin/build-lock.json

This release fixes the Dolby Vision issue when `-strict unofficial` is used, meaning we can add that flag back after this. It also improves `scale_cuda` to have nicer interpolation algorithms besides bilinear.

chore(server): upgrade ffmpeg to 7.0.2-5

---

server/bin/build-lock.json

This fixes an edge case when decoding with RKMPP.

chore: bump ffmpeg to 7.0.2-7

---

.github/workflows/docker.yml

To be removed when next buildkit version is out

fix: pin buildkit version

---

.github/workflows/docker.yml

chore: remove buildkit pin

---

server/bin/build-lock.json

This PR updates libraw to use the 2025-02 snapshot with wider camera and format compatibility, including for Samsung phones.
We changed from a snapshot to the September 0.21.3 release, but libraw patch releases apparently only cherry pick fixes without adding camera or format support. This PR effectively fixes many regressions in RAW support caused by not using a snapshot release.

chore: bump libraw

---

server/bin/build-lock.json

It has some bug fixes, including a few that could cause crashes.

chore: bump libheif to 1.19.7

---

server/bin/build-lock.json

sharp needs to be updated to `v0.34.0`

chore: update libvips

---

server/packages/ffmpeg.json

The main relevant changes for us include DoVi decoding support for RKMPP, YUV colorspace negotiation, Vulkan-based hardware encoding, a `qsv_params` filter, a variety of decoders for new codecs like VVC and xHE-AAC, tone-mapping fixes, and many arm64 optimizations.
Tested on CPU and QSV.

chore: upgrade ffmpeg to 7.1.1-3

---

postgres/Dockerfile

It is not `docker-compose.yml`, so you don't need to escape the `$`.

fix(postgres): unescape `$` for health check

---

postgres/Dockerfile
postgres/docker-compose.yml

This change will set /etc/postgresql folder to permissions 1777 which will allow any user to write a file to the /etc/postgresql folder which will allow our config file to be created. Once it is created there, no other user will be able to modify or delete that file in any way due to setting the sticky bit in the permissions and the file itself being created with 644 permissions.
This is the directory layout and permissions after this change for /etc/postgres when running with `user: 1001:1001`
Fixes immich-app/immich#18431

fix: allow any user to write to /etc/postgresql for rootless setups

---

postgres/Dockerfile

Fix a missing whitespace. It prevented adding _vectors suffix while installing pgvectors 0.3.0.
The issue raised by [@urbaman](https://github.com/urbaman) at https://github.com/immich-app/immich/issues/18431#issuecomment-2904067477.
Installation fails only on pg17 because
- For pg17 only deb with _vectors suffix was released at https://github.com/tensorchord/pgvecto.rs/releases/tag/v0.3.0:
- vectors-pg17_0.3.0_amd64_vectors.deb
- For earlier PG versions there are two debs - with and without _vectors suffix:
- vectors-pg16_0.3.0_amd64_vectors.deb
- vectors-pg16_0.3.0_amd64.deb
Why didn't the docker image build job fail? It seems `if` eats an error:
```
if [ "$PGVECTORS_TAG" = '0.3.0']; then echo "_vectors"; fi ; echo $?
bash: [: missing `]'
0
[ "$PGVECTORS_TAG" = '0.3.0'] && echo …
```

Fix pgvecto.rs 0.3.0 installation on Postgres 17

---

postgres/immich-docker-entrypoint.sh

ACLs on the host filesystem can cause a standard copy to not create the new file as 644 and then the postgres user cannot read the file. overlay2 takes the ACL from the base image on the filesystem when merging them with overlayfs

fix: preserve postgres config permissions to ensure 644

---

server/sources/libheif.json

libheif v1.19.8 does not properly detect corrupted HEIC and spins in an infinite loop with full 1 core 100% CPU usage (per thread / thumbnail generation job).
Seems fixed in v1.20, see the main issue thread.
- main issue https://github.com/immich-app/immich/issues/14349
- duplicate https://github.com/immich-app/immich/issues/20516
- libheif issue: https://github.com/strukturag/libheif/pull/1492
Another/unrelated noticeable change in v1.20:
> You can specify a security limit for the maximum total memory libheif may use for decoding. This is easier to handle than specifying limits on the maximum image size or single memory allocations.

chore: update libheif to fix 100% CPU usage due to corrupted HEIC images
